#pragma config(Sensor, S1,     ,               sensorTouch)
#pragma config(Sensor, S4,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

   	sendMessageWithParm(1000, 1000, 1000);
   		nxtDisplayTextLine(1,"***sending 25***" );
		wait1Msec(300);

	int flag1=0,flag0=0;
	while(true)
    {
    	if(SensorValue[S1]==1)
    	{

    	//	sendMessageWithParm(25, 25, 25);
    		 eraseDisplay();
    		 nxtDisplayTextLine(3,"Abort?");
    	//	 nxtDisplayTextLine(3,"Abort?");
		nxtDisplayTextLine(4,"Press small square");
		sendMessageWithParm(-1, -1, -1);
    		 wait1Msec(300);
	}
    	nxtDisplayTextLine(5,"%d", SensorValue[S4] );
		wait1Msec(300);

		if(flag0==0 && (SensorValue[S4]>45 && SensorValue[S4]<55))
    	  {
    	  		flag0=1;
    	  		nxtDisplayTextLine(1,"sending %d", SensorValue[S4] );
		wait1Msec(300);
    	  	sendMessageWithParm(10, 10, 10);
    	  	 wait1Msec(300);
      //   sendMessageWithParm(25, 25, 25);

    	}
    	  /*		motor[motorB]=0;
		motor[motorC]=0;
		wait1Msec(300);
		grab();
    	  }*/

     if(flag1==0 && (SensorValue[S4]>20 && SensorValue[S4]<30))
       {	flag1=1;
         nxtDisplayTextLine(1,"sending %d", SensorValue[S4] );
		wait1Msec(300);
         sendMessageWithParm(50, 50, 50);
         wait1Msec(300);
        // sendMessageWithParm(25, 25, 25);
      }
    /*	wait1Msec(100);
	motor[motorB]=0;
		motor[motorC]=0;
		wait1Msec(300);
		drop();
       sendMessageWithParm(SensorValue[S4], SensorValue[S4], SensorValue[S4]);

   }*/

}
}
